name: firebase_init_example

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # firebase integration
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0

  # download image
  http: ^0.12.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true